// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pass.Models;

#nullable disable

namespace pass.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230220181552_pass")]
    partial class pass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("pass.Models.Passanger", b =>
                {
                    b.Property<int>("IdPassanger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPassanger");

                    b.ToTable("Passangers");
                });

            modelBuilder.Entity("pass.Models.Point", b =>
                {
                    b.Property<int>("IdPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPoint");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("pass.Models.Ticket", b =>
                {
                    b.Property<Guid>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataArriva")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassangerIdPassanger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointArrivalIdPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointDepartureIdPoint")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTicket");

                    b.HasIndex("PassangerIdPassanger");

                    b.HasIndex("PointArrivalIdPoint");

                    b.HasIndex("PointDepartureIdPoint");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("pass.Models.Ticket", b =>
                {
                    b.HasOne("pass.Models.Passanger", "Passanger")
                        .WithMany()
                        .HasForeignKey("PassangerIdPassanger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pass.Models.Point", "PointArrival")
                        .WithMany()
                        .HasForeignKey("PointArrivalIdPoint")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pass.Models.Point", "PointDeparture")
                        .WithMany()
                        .HasForeignKey("PointDepartureIdPoint")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passanger");

                    b.Navigation("PointArrival");

                    b.Navigation("PointDeparture");
                });
#pragma warning restore 612, 618
        }
    }
}
